// src/hooks/useLanguage.tsx
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'uk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uk: {
    'layout.subtitle': '',
    'layout.title': 'Кошторис',
    'layout.user_profile': 'Профіль користувача',
    'layout.nav': 'Навігація',
    'layout.nav.overview': 'Огляд',
    'layout.nav.transactions': 'Транзакції',
    'layout.nav.analytics': 'Аналітика',
    'layout.nav.settings': 'Налаштування',
    'layout.system': 'Система',
    'layout.sign_out': 'Вийти',
    'layout.db_status': '',
    'layout.db_stable': '',
    'layout.footer_stack': 'Версія 3.1.0',
    'layout.footer_copy': '© 2026 Особистий Бюджет',
    'dashboard.loading': 'Завантаження записів...',
    'dashboard.net_liquidity': 'Чиста Ліквідність',
    'dashboard.monthly_inc': 'Доходи',
    'dashboard.monthly_exp': 'Витрати',
    'dashboard.recent_activity': 'Остання активність',
    'dashboard.no_activity': 'Немає активності',
    'dashboard.date': 'Дата',
    'dashboard.category': 'Категорія',
    'dashboard.entity': 'Опис',
    'dashboard.amount': 'Сума',
    'dashboard.unspecified': 'Не вказано',
    'dashboard.cashflow_dynamics': 'Динаміка Грошових Потоків',
    'dashboard.insufficient_data': 'Недостатньо даних',
    'dashboard.income_label': 'Дохід',
    'dashboard.expense_label': 'Витрата',
    'dashboard.financial_insight': 'Фінансовий Аналіз',
    'dashboard.insight_positive': '"Ваша чиста ліквідність залишається позитивною. Розгляньте можливість перерозподілу надлишку у резервний фонд."',
    'dashboard.insight_negative': '"Ваші витрати перевищили доходи. Перегляньте останню активність для виявлення можливих зон скорочення витрат."',
    'transactions.title': 'Транзакції',
    'transactions.add_record': '+ Додати Запис',
    'transactions.close_form': 'Закрити форму',
    'transactions.new_record': 'Новий Запис',
    'transactions.op_type': 'Тип операції',
    'transactions.expense': 'Витрата',
    'transactions.income': 'Дохід',
    'transactions.category_label': 'Категорія',
    'transactions.select_category': 'Оберіть категорію',
    'transactions.amount_label': 'Сума',
    'transactions.date_label': 'Дата',
    'transactions.desc_label': 'Опис',
    'transactions.optional': 'Опціонально',
    'transactions.cancel': 'Скасувати',
    'transactions.save_record': 'Зберегти запис',
    'transactions.search_desc': 'Пошук за описом...',
    'transactions.all_records': 'Всі записи',
    'transactions.inc_only': 'Тільки доходи',
    'transactions.exp_only': 'Тільки витрати',
    'transactions.th_date': 'Дата',
    'transactions.th_category': 'Категорія',
    'transactions.th_entity': 'Опис',
    'transactions.th_amount': 'Сума',
    'transactions.th_action': 'Дія',
    'transactions.loading': 'Завантаження...',
    'transactions.no_records': 'Записів не знайдено.',
    'transactions.unspecified': 'Не вказано',
    'transactions.del': 'ВИД',
    // ── NEW: filters & sorting ──
    'transactions.filters':        'Фільтри',
    'transactions.all_categories': 'Всі категорії',
    'transactions.date_range':     'Діапазон дат',
    'transactions.amount_range':   'Діапазон суми',
    'transactions.amount_from':    'Від',
    'transactions.amount_to':      'До',
    'transactions.reset_filters':  'Скинути фільтри',
    'transactions.records_found':  'записів',
    'analytics.title': 'Аналітика та Звіти',
    'analytics.loading': 'Завантаження аналітики...',
    'analytics.trail_month': 'Останній Місяць',
    'analytics.trail_quarter': 'Останній Квартал',
    'analytics.trail_year': 'Останній Рік',
    'analytics.no_records': 'Не знайдено записів за обраний період.',
    'analytics.period_dynamics': 'Динаміка за період',
    'analytics.exp_distribution': 'Розподіл Витрат',
    'analytics.no_recorded_exp': 'Немає записаних витрат',
    'analytics.income': 'Дохід',
    'analytics.expense': 'Витрата',
    'settings.title': 'Конфігурація Системи',
    'settings.preferences': 'Налаштування',
    'settings.primary_currency': 'Основна валюта',
    'settings.currency_uah': 'Українська гривня (UAH)',
    'settings.currency_usd': 'Долар США (USD)',
    'settings.currency_eur': 'Євро (EUR)',
    'settings.reporting_period': 'Звітний період',
    'settings.period_month': 'Місячний',
    'settings.period_quarter': 'Квартальний',
    'settings.period_year': 'Річний',
    'settings.commit_changes': 'Застосувати зміни',
    'settings.committing': 'Застосування...',
    'settings.class_registry': 'Реєстр Класифікацій',
    'settings.cat_entity': 'Назва категорії',
    'settings.cat_placeholder': 'Напр., Логістика, Операції',
    'settings.cat_type': 'Тип',
    'settings.cat_expense': 'Витрата',
    'settings.cat_income': 'Дохід',
    'settings.append': 'Додати',
    'settings.outflow': 'Відтік',
    'settings.inflow': 'Приплив',
    'settings.remove': 'Видалити',
    'auth.ledger': 'Кошторис',
    'auth.login_title': 'Автентифікація',
    'auth.register_title': 'Ініціалізація',
    'auth.identity': 'Email',
    'auth.identity_placeholder': '',
    'auth.passphrase': 'Пароль',
    'auth.passphrase_placeholder': '',
    'auth.verify_passphrase': 'Підтвердити пароль',
    'auth.verify_placeholder': '',
    'auth.enter_system': 'Увійти в систему',
    'auth.processing': 'Обробка...',
    'auth.establish': 'Створити Реєстр',
    'auth.lacking_clearance': 'Не маєте доступу?',
    'auth.initialize': 'Зареєструватися',
    'auth.already_holding': 'Вже маєте доступ?',
    'auth.pass_mismatch': 'Паролі не співпадають',
    // ── NEW: forgot/reset password ──
    'auth.forgot_link':         'Забули пароль?',
    'auth.forgot_title':        'Відновлення Доступу',
    'auth.forgot_desc':         'Введіть email вашого облікового запису і ми надішлемо посилання для відновлення паролю.',
    'auth.forgot_check_spam':   'Не отримали листа? Перевірте папку "Спам" або повторіть спробу.',
    'auth.send_reset_link':     'Надіслати Посилання',
    'auth.reset_sent':          'Якщо вказаний email зареєстровано, інструкції надіслано на нього.',
    'auth.reset_error':         'Помилка надсилання. Спробуйте пізніше.',
    'auth.back_to_login':       'Повернутись до входу',
    'auth.reset_title':         'Новий Пароль',
    'auth.reset_invalid_token': 'Посилання для відновлення недійсне або прострочене. Запросіть нове.',
    'auth.request_new_link':    'Запросити нове посилання',
    'auth.reset_success':       'Пароль успішно змінено. Зараз вас перенаправлять на сторінку входу.',
    'auth.redirect_login':      'Перенаправлення...',
    'auth.new_passphrase':      'Новий Пароль',
    'auth.set_new_password':    'Встановити Пароль',
    'auth.pass_too_short':      'Пароль повинен містити мінімум 6 символів',
  },
  en: {
    'layout.subtitle': 'Account Statement',
    'layout.title': 'Personal Ledger',
    'layout.user_profile': 'User Profile',
    'layout.nav': 'Navigation',
    'layout.nav.overview': 'Overview',
    'layout.nav.transactions': 'Transactions',
    'layout.nav.analytics': 'Analytics',
    'layout.nav.settings': 'Settings',
    'layout.system': 'System',
    'layout.sign_out': 'Sign Out',
    'layout.db_status': '',
    'layout.db_stable': '',
    'layout.footer_stack': 'Version 3.1.0',
    'layout.footer_copy': '© 2026 Personal Budget',
    'dashboard.loading': 'Loading ledger...',
    'dashboard.net_liquidity': 'Net Liquidity',
    'dashboard.monthly_inc': 'Income',
    'dashboard.monthly_exp': 'Expenses',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.no_activity': 'No recent activity',
    'dashboard.date': 'Date',
    'dashboard.category': 'Category',
    'dashboard.entity': 'Description',
    'dashboard.amount': 'Amount',
    'dashboard.unspecified': 'Unspecified',
    'dashboard.cashflow_dynamics': 'Cashflow Dynamics',
    'dashboard.insufficient_data': 'Insufficient data',
    'dashboard.income_label': 'Income',
    'dashboard.expense_label': 'Expense',
    'dashboard.financial_insight': 'Financial Insight',
    'dashboard.insight_positive': '"Your net liquidity remains positive. Consider reallocating surplus into your reserve fund."',
    'dashboard.insight_negative': '"Your expenses have outpaced income. Review recent activity to identify potential reduction areas."',
    'transactions.title': 'Transactions',
    'transactions.add_record': '+ Add Record',
    'transactions.close_form': 'Close Form',
    'transactions.new_record': 'New Record',
    'transactions.op_type': 'Operation Type',
    'transactions.expense': 'Expense',
    'transactions.income': 'Income',
    'transactions.category_label': 'Category',
    'transactions.select_category': 'Select Category',
    'transactions.amount_label': 'Amount',
    'transactions.date_label': 'Date',
    'transactions.desc_label': 'Description',
    'transactions.optional': 'Optional',
    'transactions.cancel': 'Cancel',
    'transactions.save_record': 'Save Record',
    'transactions.search_desc': 'Search descriptions...',
    'transactions.all_records': 'All Records',
    'transactions.inc_only': 'Income Only',
    'transactions.exp_only': 'Expenses Only',
    'transactions.th_date': 'Date',
    'transactions.th_category': 'Category',
    'transactions.th_entity': 'Description',
    'transactions.th_amount': 'Amount',
    'transactions.th_action': 'Action',
    'transactions.loading': 'Loading...',
    'transactions.no_records': 'No records found.',
    'transactions.unspecified': 'Unspecified',
    'transactions.del': 'DEL',
    // ── NEW: filters & sorting ──
    'transactions.filters':        'Filters',
    'transactions.all_categories': 'All Categories',
    'transactions.date_range':     'Date Range',
    'transactions.amount_range':   'Amount Range',
    'transactions.amount_from':    'From',
    'transactions.amount_to':      'To',
    'transactions.reset_filters':  'Reset filters',
    'transactions.records_found':  'records',
    'analytics.title': 'Analytics & Reporting',
    'analytics.loading': 'Loading analytics...',
    'analytics.trail_month': 'Trailing Month',
    'analytics.trail_quarter': 'Trailing Quarter',
    'analytics.trail_year': 'Trailing Year',
    'analytics.no_records': 'No records found for the selected period.',
    'analytics.period_dynamics': 'Period Dynamics',
    'analytics.exp_distribution': 'Expense Distribution',
    'analytics.no_recorded_exp': 'No recorded expenses',
    'analytics.income': 'Income',
    'analytics.expense': 'Expense',
    'settings.title': 'System Configuration',
    'settings.preferences': 'Preferences',
    'settings.primary_currency': 'Primary Currency',
    'settings.currency_uah': 'Ukrainian Hryvnia (UAH)',
    'settings.currency_usd': 'US Dollar (USD)',
    'settings.currency_eur': 'Euro (EUR)',
    'settings.reporting_period': 'Reporting Period',
    'settings.period_month': 'Monthly',
    'settings.period_quarter': 'Quarterly',
    'settings.period_year': 'Annually',
    'settings.commit_changes': 'Commit Changes',
    'settings.committing': 'Committing...',
    'settings.class_registry': 'Classification Registry',
    'settings.cat_entity': 'Category Name',
    'settings.cat_placeholder': 'E.g., Logistics, Operations',
    'settings.cat_type': 'Type',
    'settings.cat_expense': 'Expense',
    'settings.cat_income': 'Income',
    'settings.append': 'Append',
    'settings.outflow': 'Outflow',
    'settings.inflow': 'Inflow',
    'settings.remove': 'Remove',
    'auth.ledger': 'Financial Ledger',
    'auth.login_title': 'Authenticate',
    'auth.register_title': 'Initialization',
    'auth.identity': 'Identity (Email)',
    'auth.identity_placeholder': 'identity@example.com',
    'auth.passphrase': 'Passphrase',
    'auth.passphrase_placeholder': 'Signature code',
    'auth.verify_passphrase': 'Verify Passphrase',
    'auth.verify_placeholder': 'Confirm code',
    'auth.enter_system': 'Enter System',
    'auth.processing': 'Processing...',
    'auth.establish': 'Establish Registry',
    'auth.lacking_clearance': 'Lacking clearance?',
    'auth.initialize': 'Initialize',
    'auth.already_holding': 'Already holding clearance?',
    'auth.pass_mismatch': 'Passwords do not match',
    // ── NEW: forgot/reset password ──
    'auth.forgot_link':         'Forgot passphrase?',
    'auth.forgot_title':        'Access Recovery',
    'auth.forgot_desc':         'Enter your account email and we will send you a password reset link.',
    'auth.forgot_check_spam':   "Didn't receive an email? Check your spam folder or try again.",
    'auth.send_reset_link':     'Send Reset Link',
    'auth.reset_sent':          'If the email is registered, instructions have been sent to it.',
    'auth.reset_error':         'Failed to send. Please try again later.',
    'auth.back_to_login':       'Back to login',
    'auth.reset_title':         'New Password',
    'auth.reset_invalid_token': 'The reset link is invalid or expired. Please request a new one.',
    'auth.request_new_link':    'Request new link',
    'auth.reset_success':       'Password changed successfully. You will be redirected to the login page.',
    'auth.redirect_login':      'Redirecting...',
    'auth.new_passphrase':      'New Passphrase',
    'auth.set_new_password':    'Set Password',
    'auth.pass_too_short':      'Password must be at least 6 characters',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('app_language');
      return saved === 'en' || saved === 'uk' ? saved : 'uk';
    } catch {
      return 'uk';
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try { localStorage.setItem('app_language', lang); } catch {}
  };

  const t = (key: string): string =>
    translations[language][key] ?? translations['en'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
